spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reconx_uat
    driver-class-name: org.postgresql.Driver
    username: reconx_uat
    password: reconx_uat
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    com.dbtraining.reconx: INFO